version: "2"
 
services:
   wordpress-db:
     container_name: wordpress-db
     image: mysql:5.7
     volumes:
       - /srv/docker/wordpress/db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: $ROOTPWD
       MYSQL_DATABASE: wordpress
       MYSQL_USER: $USER
       MYSQL_PASSWORD: $PWD
 
   wordpress:
     container_name: wordpress
     depends_on:
       - wordpress-db
     image: wordpress:latest
     ports:
       - 8000:80
     restart: always
     volumes:
       - /srv/docker/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
       - /srv/docker/wordpress/html:/var/www/html
     environment:
       WORDPRESS_DB_HOST: wordpress-db:3306
       WORDPRESS_DB_USER: $USER
       WORDPRESS_DB_PASSWORD: $PWD
       WORDPRESS_DB_NAME: wordpress
     
   wordpress-pma:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress-pma
    depends_on:
        - wordpress-db
    environment:
        - PMA_HOST=wordpress-db
        - PMA_PORT=3306
        - PMA_ARBITRARY=1
    #ports:
    #    - 8001:80
    restart: always
